APP_PLATFORM := android-8

# NOTE: Default CPP settings add no-exceptions no-rtti so don't need to specify

APP_PROJECT_PATH := $(NDK_PROJECT_PATH)

APP_STL := gnustl_static

$(call __ndk_info,APP_BUILD_SCRIPT: $(APP_BUILD_SCRIPT))

ifeq ($(CONFIGURATION),Debug)

APP_OPTIM := debug
APP_CPPFLAGS += -D_MOBILE -DTARGET_PLATFORM_MOBILE -DTARGET_SUBPLATFORM_ANDROID -D_DEBUG -fvisibility=hidden -g
APP_CFLAGS += -D_MOBILE -DTARGET_PLATFORM_MOBILE -DTARGET_SUBPLATFORM_ANDROID -D_DEBUG -fvisibility=hidden -g

else

APP_OPTIM := release
APP_CPPFLAGS += -D_MOBILE -DTARGET_PLATFORM_MOBILE -DTARGET_SUBPLATFORM_ANDROID -D_RELEASE -DNDEBUG -fvisibility=hidden -g
APP_CFLAGS += -D_MOBILE -DTARGET_PLATFORM_MOBILE -DTARGET_SUBPLATFORM_ANDROID -D_RELEASE -DNDEBUG -fvisibility=hidden -g

endif
